name: Deploy to Fly.io

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  deploy-backend:
    name: Deploy Express backend & worker
    runs-on: ubuntu-latest
    concurrency: deploy-backend
    steps:
      - uses: actions/checkout@v4

      # Setup Fly CLI
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      # Deploy (backend & worker)
      - name: Fly deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
